### ISSUE TITLE
Página de cadastro

### ISSUE THREAD

**Issue by gfborges** [gfborges/uol-unique-user-id#6]
**Story**
Como usuário, quero que os campos que visualizo no site sejam guardados em memória por enquanto que estou no site.
**Contextualização**
Guarde os dados de cada campo do cadastro:
 * e-mail
 * senha
 * nome
 * telefone( se possível use uma máscara conforme o site de cadastro do BOL)

**Comment by isabellefo** [comment]
Guardar os dados preenchidos no formulário em memória

**Comment by gfborges** [comment]
A página de cadastro deve se basear no layout de [cadastro no bol](https://checkout.uol.com.br/#/bol/0?promotion=WEBEMAILBOL)
