### ISSUE TITLE
Mandar o request de cadastro

### ISSUE THREAD

**Issue by gfborges** [gfborges/uol-unique-user-id#7]
**Story**
Como usuário, quero que ao finalizar o cadastro minhas informações sejam registradas na base de dados.

**Contextualização**
Ao preencher todos os campos mande um request para o back-end registrar o usuário.

**Comment by isabellefo** [comment]
Cadastrar usuário quando finalizado o preenchimento dos campos dos forms

**Comment by gfborges** [comment]
Caso o back não volte 200, exibir mensagem de erro avisando o usuário

**Comment by gfborges** [comment]
Bloqueado pela tarefa de fazer a página
