### ISSUE TITLE
Momento de inicio e fim do cadastro

### ISSUE THREAD

**Issue by gfborges** [gfborges/uol-unique-user-id#8]
**Story**
Como usuário, quero saber o momento de início e fim do cadastro.

**Contextualização**
Registre o momento (data e hora) em que o usuário começa a preencher o cadastro e o momento em que faz a requisição de cadastro para o back-end

**Comment by isabellefo** [comment]
Guardar data e hora do momento que o usuário iniciou o preenchimento do dados

**Comment by gfborges** [comment]
Sugestão começe a contar quando o usuário entra na página
